apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: streamsets-datacollector-hpa
  namespace: streamsets
  labels:
    app: streamsets-datacollector
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: streamsets-datacollector
  minReplicas: 1
  maxReplicas: 1  # Limitado devido à natureza stateful do StreamSets
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
