apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streamsets-data-pvc
  namespace: streamsets
  labels:
    app: streamsets-datacollector
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: microk8s-hostpath

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streamsets-logs-pvc
  namespace: streamsets
  labels:
    app: streamsets-datacollector
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: microk8s-hostpath

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streamsets-resources-pvc
  namespace: streamsets
  labels:
    app: streamsets-datacollector
spec:
  accessModes:
    - ReadWriteOnce  # Mudando para RWO pois microk8s-hostpath não suporta RWX
  resources:
    requests:
      storage: 2Gi
  storageClassName: microk8s-hostpath
